config/routes.rb
Rails.application.routes.draw do
  get 'con_verificadors/index'
  root "homes#index"
  post 'empresas/:empresa_id/aspiracions/update_maturity_recomendation', to: 'aspiracions#update_maturity_recomendation', as: 'update_maturity_recomendation'
  post 'empresas/:empresa_id/aspiracions/update_dat_recomendation', to: 'aspiracions#update_dat_recomendation', as: 'update_dat_recomendation'
  post 'empresas/:empresa_id/aspiracions/update_hab_recomendation', to: 'aspiracions#update_hab_recomendation', as: 'update_hab_recomendation'
  post 'empresas/:empresa_id/users/invite_member', to: 'users#invite_member', as: 'invite_member'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    invitations: 'users/invitations'
  }, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get "empresas/:empresa_id/users", to: "users#index", as: "empresa_users"
  get "users/:id", to: "users#show", as: "user"
  resources :empresas, only: [:show] do 
    resources :areas, only: [:create]
    resources :itdcons, only: [:index, :show, :create, :update, :destroy] do
      resources :itdinds, only: [:show, :edit, :update]
      resources :itdareas, only: [:show, :update]
      resources :com_verificadors, only: [:index]
    end
    resources :aspiracions, only: [:index, :show, :create, :update]
  end
  resources :itdsins , only: [:new, :create, :show]
  get "homes/example"

  get '/*paths', to: 'unhandled#show'
end

app/models/itdcon.rb
class Itdcon < ApplicationRecord
  belongs_to :empresa
  belongs_to :madurez, optional: true
  belongs_to :alineamiento, optional: true
  has_many :itdinds, dependent: :destroy
  has_many :itdareas, dependent: :destroy

end

app/controllers/itdcons_controller.rb
class ItdconsController < ApplicationController
  before_action :get_itdcon, only: [ :show, :update, :destroy ]
  before_action :get_empresa
  before_action :get_participants, only: [ :index, :create, :update]
  before_action :authenticate_user!
  before_action :correct_user
  before_action :correct_user_admin, only: [ :create, :update, :destroy ]
  before_action :itdcon_pending, only: [ :create]
  before_action :correct_empresa, except: [:index, :create]
  before_action :correct_completed, only: [ :show]
  before_action :not_completed, only: [ :update, :destroy]
  before_action :get_points, only: [ :show]

  def index
    @itdcons = @empresa.itdcons.order(id: :asc)
    get_all_points
    @last_itdcon = @itdcons.where(completed: true).last
    @last_not_completed_itdcon = @itdcons.find_by(completed: false)
  end

  def create
    @itdcon = @empresa.itdcons.build()
    @itdind = nil
    #ADD any_participant_selected
    #respond_to do |format|
    @itdcon_params = create_params
    puts "Values: #{@itdcon_params}"
    puts "Areas: #{@empresa.areas.length}"
    puts "Users: #{@empresa.user_ids}"
    if @itdcon_params.values.include? "1"
      if @itdcon.save
        if @empresa.areas.length == 0
          @itdcon_params.keys.each do |param|
            if @itdcon_params[param].to_i == 1
              user = @empresa.users.find_by(id: param.to_i) #Cambiar a paerticipants
              if user != current_user 
                itdind = user.itdinds.build()
                itdind.itdcon = @itdcon
                itdind.save()
              else
                puts "AAAA"
                @itdind = current_user.itdinds.build()
                @itdind.itdcon = @itdcon
                @itdind.save
              end
            end
          end
        else
          @itdcon_params.keys.each do |param|
            if @itdcon_params[param].to_i == 1
              itdarea = @itdcon.itdareas.build
              area = Area.find_by(id: param.to_i)
              itdarea.area = area
              if itdarea.save
                area.users.each do |user|
                  itdind = user.itdinds.build()
                  itdind.itdcon = @itdcon
                  itdind.itdarea = itdarea
                  itdind.save()
                end
              end
            end
          end
        end
        if @itdind
          redirect_to edit_empresa_itdcon_itdind_path(@empresa, @itdcon, @itdind)
        else
          redirect_to empresa_itdcons_path(@empresa.id)
        end
      else #REVISAR EL ELSE
        redirect_to empresa_itdcons_path(@empresa.id)
      end
    else
      redirect_to empresa_itdcons_path(@empresa.id), notice: "Debe elegir al menos un miembro para realizar el ITD"
    end
  end

  def show
  end

  def update
    @itdcon_params = update_params
    itdind_ids = []
    if @itdcon.itdareas.length == 0
      @itdcon.itdinds.each do |itd|
        itdind_ids.push(itd.user_id)
      end
    else
      @itdcon.itdareas.each do |itd|
        itdind_ids.push(itd.area_id)
      end
    end
    new_itdinds = []
    delete_itdinds = []
    @itdind = nil
    @itdcon_params.keys.each do |key|
      if @itdcon_params[key] == "1"
        new_itdinds.push(key.to_i)
      end
      if @itdcon_params[key] == "0" 
        if itdind_ids.include? key.to_i
          delete_itdinds.push(key.to_i)
        end
      end
    end
    if new_itdinds.length > 0
      if @itdcon.itdareas.length == 0
        new_itdinds.each do |param|
          if @itdcon.itdinds.find_by(user_id: param) == nil
            user = User.find_by(id: param.to_i) #Cambiar a participants
            if user != current_user
              itdind = user.itdinds.build()
              itdind.itdcon = @itdcon
              itdind.save()
            else
              @itdind = current_user.itdinds.build()
              @itdind.itdcon = @itdcon
              @itdind.save
            end
          end
        end
        if delete_itdinds.length > 0
          delete_itdinds.each do |param|
            itdind = @itdcon.itdinds.find_by(user_id: param)
            itdind.delete
          end
        end
      else
        new_itdinds.each do |param|
          if @itdcon.itdareas.find_by(area_id: param) == nil
            itdarea = @itdcon.itdareas.build
            area = Area.find_by(id: param.to_i)
            itdarea.area = area
            if itdarea.save
              area.users.each do |user|
                itdind = user.itdinds.build()
                itdind.itdcon = @itdcon
                itdind.itdarea = itdarea
                itdind.save()
              end
            end
          end
        end
        if delete_itdinds.length > 0
          delete_itdinds.each do |param|
            itdarea = @itdcon.itdareas.find_by(area_id: param)
            itdarea.delete
          end
        end
      end
      check_if_completed
      if @itdind
        redirect_to edit_empresa_itdcon_itdind_path(@empresa, @itdcon, @itdind)
      else
        redirect_to empresa_itdcons_path(@empresa.id), notice: "Medición actualizados."
      end
    else
      redirect_to empresa_itdcons_path(@empresa.id), notice: "Debe elegir al menos un miembro para realizar el ITD"
    end
  end

  def destroy
    if @itdcon.delete
      redirect_to empresa_itdcons_path(@empresa), notice: "Medición eliminada con éxito"
    else
      redirect_to empresa_itdcons_path(@empresa), notice: "Ocurrió un error al eliminar la medición"
    end
  end
  private

  def check_if_completed
    if @itdcon.itdareas.length > 0
      @itdcon.itdareas.each do |itdarea|
        calculate_bigger_itd itdarea, itdarea.itdinds
      end
      calculate_bigger_itd @itdcon, @itdcon.itdareas
    else
      calculate_bigger_itd @itdcon, @itdcon.itdinds
    end
  end

  def calculate_bigger_itd itd, itd_collection
    itdinds = itd_collection.where(completed: true)
    if itdinds.length == itd_collection.count
      itd[:completed] = true
    else
      itd[:completed] = false
    end
     #Atomicidad, y si dos cambian a true al mismo tiempo?
    if itd[:completed] == true
      Driver.all.each do |driver|
        itd[driver.identifier] = 0
        itdinds.each do |itdind|
          itd[driver.identifier] += itdind[driver.identifier]
        end
        itd[driver.identifier] = itd[driver.identifier]/itdinds.length.to_f
      end
      itd["maturity_score"] = 0
      itd["alignment_score"] = 0
      itdinds.each do |itdind|
        itd["maturity_score"] += itdind["maturity_score"]
        itd["alignment_score"] += itdind["alignment_score"]
      end
      itd["maturity_score"] = itd["maturity_score"]/itdinds.length.to_f
      itd["alignment_score"] = itd["alignment_score"]/itdinds.length.to_f
      Madurez.all.each do |level| #HACER LO MISMO PARA LOS IND
        if itd["maturity_score"] <= level.max and itd["maturity_score"] >= level.min
          itd.madurez = level
          break
        end
      end
      Alineamiento.all.each do |level|
        if itd["alignment_score"] <= level.max and itd["alignment_score"] >= level.min
          itd.alineamiento = level
          break
        end
      end
    end
    itd.save
  end

  def correct_user
    redirect_to root_path, notice: "No tienes permiso realizar esa acción." if @empresa != current_user.empresa
  end

  def correct_user_admin
    redirect_to empresa_itdcons_path(@empresa.id), notice: "Solo el administrador puede realizar esa acción." if current_user.is_admin == "0"
  end

  def itdcon_pending
    redirect_to empresa_itdcons_path(@empresa.id), notice: "Aún hay una medición pendiednte." if @empresa.itdcons.find_by(completed: false) != nil
  end

  def correct_completed
    redirect_to empresa_itdcons_path(@empresa.id), notice: "Todos deben responder la encuesta antes de ver los resultados." if (!@itdcon.completed)
  end

  def not_completed
    redirect_to empresa_itdcons_path(@empresa.id), notice: "No puede agregar miembros a una medición finalizada." if (@itdcon.completed) #Validar
  end

  def correct_empresa
    redirect_to root_path, notice: "No tienes permiso realizar esa acción." if @empresa != @itdcon.empresa
  end

  def get_itdcon
    @itdcon = Itdcon.find_by(id: params[:id])
  end

  def get_points
    @points_dat = {}
    @points_hab = {}
    Dat.all.each do |dat|
      point_dat = 0
      dat.habilitadors.each do |habilitador|
        point_habilitador = 0
        habilitador.elementos.each do |elemento|
          point_elemento = 0
          elemento.drivers.each do |driver|
            point_elemento += @itdcon[driver.identifier]
          end
          point_elemento = point_elemento/elemento.drivers.count.to_f
          point_elemento = point_elemento*100/4.to_f
          point_habilitador += point_elemento 
        end
        point_habilitador = point_habilitador/habilitador.elementos.count.to_f
        @points_hab[habilitador.name.downcase] = point_habilitador
        point_dat += point_habilitador
      end
      point_dat = point_dat/dat.habilitadors.count.to_f
      @points_dat[dat.name.downcase] = point_dat
    end
  end

  def get_all_points
    @all_points_dat = {}
    @itdcons.where(completed: true).each do |itd|
      @all_points_dat[itd.id] = {}
      Dat.all.each do |dat|
        point_dat = 0
        dat.habilitadors.each do |habilitador|
          point_habilitador = 0
          habilitador.elementos.each do |elemento|
            point_elemento = 0
            elemento.drivers.each do |driver|
              point_elemento += itd[driver.identifier]
            end
            point_elemento = point_elemento/elemento.drivers.count.to_f
            point_elemento = point_elemento*100/4.to_f
            point_habilitador += point_elemento 
          end
          point_habilitador = point_habilitador/habilitador.elementos.count.to_f
          point_dat += point_habilitador
        end
        point_dat = point_dat/dat.habilitadors.count.to_f
        @all_points_dat[itd.id][dat.name.downcase] = point_dat
      end
    end
  end
  

app/helpers/itdcons_helper.rb
module ItdconsHelper
end

app/views/itdcons/_edit.html.erb
<div class="modal fade" id="editItdconModal" tabindex="-1" aria-labelledby="editItdconModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <%if itdcon.itdareas.length == 0%>
          <h1 class="modal-title fs-5" id="editItdconModalLabel">Elija los participantes de la medición</h1>
        <%else%>
          <h1 class="modal-title fs-5" id="editItdconModalLabel">Elija las áreas que participaran de la medición</h1>
        <%end%>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%if itdcon.itdareas.length == 0%>
          <%= render partial: "form", locals: {empresa: empresa, itdcon: itdcon, participants: participants}%>
        <%else%>
          <%= render partial: "form_area", locals: {empresa: empresa, itdcon: itdcon, areas: empresa.areas}%>
        <%end%>
      </div>
      <div class="modal-footer d-flex flex-wrap justify-content-between align-items-center">
        <div>
          <%= link_to "Eliminar medición", [empresa, itdcon], data: { turbo_method: :delete, turbo_confirm: "¿Seguro que quiere eliminarla (se eliminarán además todas las mediciones individuales)?" }, class:"btn btn-danger mb-2 me-2" %>
        </div>
        <div>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary" name="submit" value="Submit" form="itdcon_form" onclick="return confirm('¿Está seguro? Cualquier medición desmarcada se eliminará')">Editar medición</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/itdcons/index.html.erb
<div class="main mt-4">
  <div class="d-flex flex-wrap justify-content-between mb-3 align-items-center w-100 me-5 ">
    <h3> Mediciones Históricas </h3>
    <% if current_user.is_admin%>
      <%if @itdcons.where(completed: false).length >0%>
        <button class="btn btn-dark" disabled >
          Nuevo ITD
        </button>
      <%else%>
        <button type="button" class="btn btn-outline-primary " data-bs-toggle="modal" data-bs-target="#exampleModal">
          Nuevo ITD
        </button>
        <%= render partial: "new", locals: {empresa: @empresa, itdcon: @empresa.itdcons.build, participants: @participants}%>
      <%end%>
    <%end%>
  </div>
  <script>
    let label;
    let value;
    let color;
    let ctx;
  </script>
  <div class="row">
    <%if @last_itdcon%>
    <div class="p-3 mb-5 col-xl-5 col-lg-5 col-md-12 col-sm-12 col-xs-12 ">
    <%else%>
    <div class="p-3 mb-5 col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <%end%>
      <% @itdcons.each_with_index do |itd, index| %>
        <%if itd[:completed] and itd != @last_itdcon%>
          <%=link_to empresa_itdcon_path(@empresa.id, itd.id), data: {turbo: false}, class:"itdlink" do %>
            <div class="row m-2 rounded border border-dark bg-white">
              <b><%= 'ITD ' + l(itd.created_at.to_date, format: :custom_itd)%></b>
              <div class="d-flex flex-wrap justify-content-center align-items-around col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="d-flex flex-wrap w-100 align-items-end justify-content-around ">
                  <div>
                    <h3 class="text-center"><b><%= itd["maturity_score"].round %></b></h3>
                    <p class="text-center" style="font-size: 12px">Madurez</p>
                  </div>
                  <div>
                    <h3 class="text-center"><b><%= itd["alignment_score"].round %></b></h3>
                    <p class="text-center" style="font-size: 12px">Alineamiento</p>
                  </div>
                </div>
                <b class="text-center"><%= "#{itd.madurez.name.titleize} con #{itd.alineamiento.name.capitalize}" %></b>
              </div>
              <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 "> 
                
                <canvas id="myChart<%=itd.id%>" height="200px"></canvas>
                <script>
                  label = [];
                  colors = [];
                  values = [];
                  <% @all_points_dat[itd.id].keys.each do |dat|%>
                    label.push("<%=dat.capitalize%>");
                    values.push(<%= @all_points_dat[itd.id][dat].round%>);
                  <%end%>
                  ctx = document.getElementById('myChart<%=itd.id%>');
                    new Chart(ctx, {
                        
                        data: {
                        labels: label,
                        datasets: [{
                          label: 'Puntaje por Capital',
                          type: 'bar',
                          data: values,
                          fill: true,
                          backgroundColor: "blue",
                          borderColor:'blue'
                        }]
                      },
                        options: {
                          maintainAspectRatio: false,
                          plugins: {
                            legend: {
                              onClick: null,
                              display: false,
                            }
                          },
                          scales: {
                            y: { 
                              ticks: {
                                count: 101,
                                callback: (value, index, values ) => {
                                  if ([0,30,55,75,90,100].includes(value)) {
                                    return value
                                  };
                                }
                              },
                              min: 0, 
                              max: 100,
                            },
                          },
                          elements: {
                            line: {
                              borderWidth: 3
                            }
                          }
                        },
                      });
                </script>

              </div>
            </div>
          <%end%>
        <% end %>
      <% end %>
    </div>
    <%if @last_itdcon or @last_not_completed_itdcon%>
      <div class="p-3 mb-5 col-xl-7 col-lg-7 col-md-12 col-sm-12 col-xs-12">
        <%if @last_itdcon %>
          <%=link_to empresa_itdcon_path(@empresa.id, @last_itdcon.id), data: {turbo: false}, class:"itdlink" do %>
            <div class="row rounded m-2 border border-dark bg-white">
              <b><%= 'ITD ' + l(@last_itdcon.created_at.to_date, format: :custom_itd)%></b>
              <div class="d-flex flex-wrap justify-content-center align-items-around col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="d-flex flex-wrap w-100 align-items-end justify-content-around ">
                  <div>
                    <h3 class="text-center"><b><%= @last_itdcon["maturity_score"].round %></b></h3>
                    <p class="text-center" style="font-size: 12px">Madurez</p>
                  </div>
                  <div>
                    <h3 class="text-center"><b><%= @last_itdcon["alignment_score"].round %></b></h3>
                    <p class="text-center" style="font-size: 12px">Alineamiento</p>
                  </div>
                  <div>
                    <h3 class="text-center"><b><%= @last_itdcon.itdinds.count %></b></h3>
                    <p class="text-center" style="font-size: 12px">Respuestas</p>
                  </div>
                </div>
                <b class="text-center"><%= "#{@last_itdcon.madurez.name.titleize} con #{@last_itdcon.alineamiento.name.capitalize}" %></b>
              </div>
              <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 "> 
                
                <canvas id="myChart<%=@last_itdcon.id%>" height="250px"></canvas>
                <script>
                  label = [];
                  colors = [];
                  values = [];
                  <% @all_points_dat[@last_itdcon.id].keys.each do |dat|%>
                    label.push("<%=dat.capitalize%>");
                    values.push(<%= @all_points_dat[@last_itdcon.id][dat].round%>);
                  <%end%>
                  ctx = document.getElementById('myChart<%=@last_itdcon.id%>');
                    new Chart(ctx, {
                        
                        data: {
                        labels: label,
                        datasets: [{
                          label: 'Puntaje por Capital',
                          type: 'bar',
                          data: values,
                          fill: true,
                          backgroundColor: "blue",
                          borderColor:'blue'
                        }]
                      },
                        options: {
                          maintainAspectRatio: false,
                          plugins: {
                            legend: {
                              onClick: null,
                              display: false,
                            }
                          },
                          scales: {
                            y: { 
                              ticks: {
                                count: 101,
                                callback: (value, index, values ) => {
                                  if ([0,30,55,75,90,100].includes(value)) {
                                    return value
                                  };
                                }
                              },
                              min: 0, 
                              max: 100,
                            },
                          },
                          elements: {
                            line: {
                              borderWidth: 3
                            }
                          }
                        },
                      });
                </script>

              </div>
            </div>
          <%end%>
        <%end%>
        <%if @last_not_completed_itdcon%>
          <div class="row rounded border border-dark bg-white m-2 position-relative ">
            <div class="d-flex flex-wrap justify-content-between align-items-center">
              <b><%='ITD ' + l(@last_not_completed_itdcon.created_at.to_date, format: :custom_itd)%></b>
              <% if current_user.is_admin%>
                <%= render partial: "edit", locals: {empresa: @empresa, itdcon: @last_not_completed_itdcon, participants: @participants}%>
                <button type="button" class="btn btn-primary mt-2" data-bs-toggle="modal" data-bs-target="#editItdconModal">
                  Editar Medición
                </button>
              <%end%>
            </div>
            <%if @last_not_completed_itdcon.itdareas.length >0%>
              <div>
                <%@last_not_completed_itdcon.itdareas.each do |itd|%>
                  <div class="rounded border border-dark bg-white mt-2 mb-2 position-relative ps-2">
                    <b><%= "ITD de #{itd.area.name}" %></b>
                    <br>
                    <br>
                    <div>
                      <%if itd[:completed]%>
                        <p><b><%= "Todos los miembros actuales respondieron" %></b></p>
                      <%else%>
                        <p><%= "Miembros restantes:" %></p>
                        <ul>
                          <%itd.itdinds.each do |itdind|%>
                            <%if !itdind[:completed]%>
                              <%if itdind.user == current_user%>
                                <li><%=itdind.user.name%> (tu)</li>
                                <%= link_to 'Responder ITD', edit_empresa_itdcon_itdind_path(@empresa.id, @last_not_completed_itdcon.id, itdind.id), class:"btn btn-primary position-absolute top-0 end-0 mt-2 me-2"%>
                              <%else%>
                                <li><%=itdind.user.name%></li>
                              <%end%>
                            <%end%>
                          <%end%>
                        </ul>
                      <%end%>
                      <% if current_user.is_admin%>
                        <%= render partial: "itdareas/edit", locals: {empresa: @empresa, itdarea: itd, itdcon: @last_not_completed_itdcon, id: itd.area.name}%>
                        <div>
                          <button type="button" class="btn btn-primary position-absolute bottom-0 end-0 mb-2 me-2" data-bs-toggle="modal" data-bs-target="#<%=itd.area.name%>Modal">
                            Editar participantes
                          </button>
                        </div>
                      <%end%>
                    </div>
                  </div>
                <%end%>
              </div>
            <%else%>
              <br>
              <br>
              <p><%= "Miembros restantes:" %></p>
              <div>
                <ul>
                  <%@last_not_completed_itdcon.itdinds.each do |itdind|%>
                    <%if !itdind[:completed]%>
                      <%if itdind.user == current_user%>
                        <li><%=itdind.user.name%> (tu)</li>
                        <%= link_to 'Responder ITD', edit_empresa_itdcon_itdind_path(@empresa.id, @last_not_completed_itdcon.id, itdind.id), class:"btn btn-primary position-absolute bottom-0 end-0 mb-2 me-2"%>
                      <%else%>
                        <li><%=itdind.user.name%></li>
                      <%end%>
                    <%end%>
                  <%end%>
                </ul>
              </div>
            <%end%>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/itdcons/show.html.erb
<div class="main mt-4 shadow p-3 mb-5 rounded">
  <h1 class="text-center" style="margin-bottom: 60px">Resultados Consolidados medición <%=l(@itdcon.created_at.to_date, format: :custom_itd)%></h1>
  <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12"> 
      <div class=" row">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 d-flex flex-wrap justify-content-start">
          <div class="dropdown mb-2">
            <button class="btn btn-secondary dropdown-toggle" role="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
              Respuestas Consolidadas
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <% if @itdcon.itdareas.length == 0%>
                <% @itdcon.itdinds.each do |itdind|%>
                  <% if itdind.user == current_user%>
                    <li><%= link_to "Respuestas #{itdind.user.name} #{itdind.user.lastname}", empresa_itdcon_itdind_path(@empresa.id, @itdcon.id, itdind), data: {turbo: false}, class:"dropdown-item" %></li>
                  <%else%>
                    <%if current_user.is_admin%>
                      <li><%= link_to "Respuestas #{itdind.user.name} #{itdind.user.lastname}", empresa_itdcon_itdind_path(@empresa.id, @itdcon.id, itdind), data: {turbo: false}, class:"dropdown-item" %></li>
                    <%end%>
                  <%end%>
                <% end %>
              <%else%>
                <li class="dropdown dropend">
                  <% @itdcon.itdareas.each do |itdarea|%>
                    <button class="dropdown-item dropdown-toggle" id="dropdownSubMenuButton<%=itdarea.area.name%>" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Respuestas <%=itdarea.area.name%>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownSubMenuButton<%=itdarea.area.name%>">
                      <li><%= link_to "<b>Respuestas Consolidadas #{itdarea.area.name}</b>".html_safe, empresa_itdcon_itdarea_path(@empresa.id, @itdcon.id, itdarea), data: {turbo: false}, class:"dropdown-item" %></li>
                      <% itdarea.itdinds.each do |itdind|%>
                        <% if itdind.user == current_user%>
                          <li><%= link_to "Respuestas #{itdind.user.name} #{itdind.user.lastname}", empresa_itdcon_itdind_path(@empresa.id, @itdcon.id, itdind), data: {turbo: false}, class:"dropdown-item" %></li>
                        <%else%>
                          <%if current_user.is_admin%>
                            <li><%= link_to "Respuestas #{itdind.user.name} #{itdind.user.lastname}", empresa_itdcon_itdind_path(@empresa.id, @itdcon.id, itdind), data: {turbo: false}, class:"dropdown-item" %></li>
                          <%end%>
                        <%end%>
                      <% end %>
                    </ul>
                  <% end %>
                </li>
              <%end%>
            </ul>
          </div>
        </div>
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 d-flex flex-wrap justify-content-xl-end justify-content-lg-end justify-content-md-end justify-content-sm-start justify-content-xs-start">
          <div>
            <% link_to "Resultado Verificadores", empresa_itdcon_com_verificadors_url(@empresa, @itdcon), data: {turbo: false}, class:"btn btn-secondary"%>
          </div>
        </div>
      </div>
      <%= render partial: "results_graphs/maturity_result", locals: {itd: @itdcon}%>
      
      <%= render partial: "results_graphs/dat_result", locals: {itd: @itdcon, points_dat: @points_dat}%>

      <%= render partial: "results_graphs/hab_result", locals: {itd: @itdcon, points_hab: @points_hab}%>

      <%= render partial: "results_graphs/cap_result", locals: {itd: @itdcon, points_dat: @points_dat, points_hab: @points_hab}%>
    </div>
  </div>
  <%if current_user.is_admin%>
    <div class = "d-flex justify-content-end marginright">
      <%= link_to 'Definir aspiración', empresa_aspiracions_path(@empresa), class:"btn btn-primary" , data: {turbo: false}%>
    </div>
  <%end%>
</div>