config/routes.rb
Rails.application.routes.draw do
  get 'con_verificadors/index'
  root "homes#index"
  post 'empresas/:empresa_id/aspiracions/update_maturity_recomendation', to: 'aspiracions#update_maturity_recomendation', as: 'update_maturity_recomendation'
  post 'empresas/:empresa_id/aspiracions/update_dat_recomendation', to: 'aspiracions#update_dat_recomendation', as: 'update_dat_recomendation'
  post 'empresas/:empresa_id/aspiracions/update_hab_recomendation', to: 'aspiracions#update_hab_recomendation', as: 'update_hab_recomendation'
  post 'empresas/:empresa_id/users/invite_member', to: 'users#invite_member', as: 'invite_member'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    invitations: 'users/invitations'
  }, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get "empresas/:empresa_id/users", to: "users#index", as: "empresa_users"
  get "users/:id", to: "users#show", as: "user"
  resources :empresas, only: [:show] do 
    resources :areas, only: [:create]
    resources :itdcons, only: [:index, :show, :create, :update, :destroy] do
      resources :itdinds, only: [:show, :edit, :update]
      resources :itdareas, only: [:show, :update]
      resources :com_verificadors, only: [:index]
    end
    resources :aspiracions, only: [:index, :show, :create, :update]
  end
  resources :itdsins , only: [:new, :create, :show]
  get "homes/example"

  get '/*paths', to: 'unhandled#show'
end

app/models/aspiracion.rb
class Aspiracion < ApplicationRecord
  belongs_to :empresa
  validates_presence_of :maturity_score, :alignment_score, :estratégico, :estructural, :humano, :relacional, :natural, :estrategia, :modelos_de_negocios, :governance, :procesos, :tecnología, :datos_y_analítica, :modelo_operativo, :propiedad_intelectual, :personas, :ciclo_de_vida_del_colaborador, :estructura_organizacional, :stakeholders, :marca, :clientes, :sustentabilidad
end

app/controllers/aspiracions_controller.rb
class AspiracionsController < ApplicationController
  before_action :get_empresa
  before_action :authenticate_user!
  before_action :exists_aspiracion, only: [ :show] 
  before_action :get_aspiracion
  before_action :get_last_itdcon, only: [ :index, :show, :create, :update, :update_maturity_recomendation, :update_dat_recomendation, :update_hab_recomendation  ]
  before_action :get_recomendation, only: [:index, :create, :update]
  respond_to :js, :json, :html
  before_action :correct_user
  before_action :correct_admin, only: [:index, :create, :update, :update_maturity_recomendation, :update_dat_recomendation, :update_hab_recomendation]
  before_action :correct_empresa, only: [:show]

  def index
  end

  def show
    @itdcons = @empresa.itdcons.all
    get_points #get element and driver points and recomendations
    @recomendation_element = {}
    @recomendation_driver = {}
    puts "AAAA"
    print @get_last_itdcon
    puts @aspiracion
    puts @points_hab
    calculate_element_driver_recomendation
  end

  def create
    @aspiracion = @empresa.build_aspiracion(aspiracion_params)
    respond_to do |format|
      if @aspiracion.save
        format.html { redirect_to empresa_aspiracion_path(@empresa, @aspiracion), notice: "Aspiración creada con éxito." }
      else
        format.html { redirect_to empresa_aspiracions_path(@empresa.id), status: :unprocessable_entity }
        format.json { render json: @aspiracion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @aspiracion = @empresa.aspiracion
    respond_to do |format|
      if @aspiracion.update(aspiracion_params)
        format.html { redirect_to empresa_aspiracion_path(@empresa, @aspiracion), notice: "Aspiración creada con éxito." }
      else
        format.html { redirect_to empresa_aspiracions_path(@empresa.id), status: :unprocessable_entity }
        format.json { render json: @aspiracion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_maturity_recomendation
    @recomendation_mat = {}
    @recomendation_dat = {}
    @recomendation_hab = {}
    @aspiracion_dat = {}
    @aspiracion_mat = {}
    @aspiracion_hab = {}
    @maturity_params = maturity_params
    @maturity_params.keys.each do |mat|
      if @maturity_params[mat] != "" and @maturity_params[mat] != nil
        @recomendation_mat[mat] = @maturity_params[mat].to_f
      else
        @recomendation_mat[mat] = @itdcon[mat]
      end
    end
    get_points
    calculate_recomendation
    @aspiracion_mat["maturity_score"] = @recomendation_mat["maturity_score"]
    calculate_alignment
    if @aspiracion_mat["alignment_score"]> @recomendation_mat["alignment_score"]
      ensure_alignment
    else
      @recomendation_mat["alignment_score"] = @aspiracion_mat["alignment_score"]
    end
    respond_to do |format|
      format.turbo_stream
      format.json {render json: @recomendation_mat}
    end
  end

  def update_dat_recomendation
    get_points
    @recomendation_mat = {}
    @dat_params = dat_params
    @recomendation_mat["alignment_score"] = @dat_params["alignment_score"].to_f
    @recomendation_mat["maturity_score"] = @dat_params["maturity_score"].to_f
    @recomendation_dat = {}
    calculate_recomendation
    @aspiracion_dat = {}
    @aspiracion_mat = {}
    @aspiracion_hab = {}
    @recomendation_hab = {}
    @points_dat.keys.each do |dat|
      if @dat_params[dat] != "" and @dat_params[dat] != nil
        @aspiracion_dat[dat] = @dat_params[dat].to_f
      else
        @aspiracion_dat[dat] = @points_dat[dat]
      end
    end
    if @aspiracion_dat == @points_dat
      @aspiracion_dat = @recomendation_dat
    end
    @aspiracion_mat["alignment_score"] = 0
    @aspiracion_mat["maturity_score"] = 0
    Dat.all.each do |dat|
      @aspiracion_mat["maturity_score"] += @aspiracion_dat[dat.name.downcase.downcase]*dat.ponderador
    end
    calculate_hab_recomendation
    if @aspiracion_dat == @points_dat
      @recomendation_hab = {}
      @aspiracion_dat = {}
    end

    respond_to do |format|
      format.json {render json: @aspiracion_dat}
      format.turbo_stream
    end
  end

  def update_hab_recomendation
    get_points
    @aspiracion_mat = {}
    @aspiracion_dat = {}
    @aspiracion_hab = {}
    @recomendation_hab = {}
    habilitadores = []
    @recomendation_mat = {}
    @hab_params = hab_params
    @recomendation_mat["alignment_score"] = @hab_params["alignment_score"].to_f
    @recomendation_mat["maturity_score"] = @hab_params["maturity_score"].to_f
    @recomendation_dat = {}
    calculate_recomendation
    @points_dat.keys.each do |dat|
      @aspiracion_dat[dat] = @hab_params[dat].to_f 
    end
    @aspiracion_mat["alignment_score"] = 0
    @aspiracion_mat["maturity_score"] = 0
    calculate_hab_recomendation
    @points_hab.keys.each do |dat|
      if dat == @hab_params[:dat]
        @aspiracion_dat[dat] = 0
        @aspiracion_hab[dat] = {}
        @points_hab[dat].keys.each do |hab|
          if @hab_params[hab] != "" and @hab_params[hab] != nil
            @aspiracion_hab[dat][hab] = @hab_params[hab].to_f
          else
            @aspiracion_hab[dat][hab] = @points_hab[dat][hab].to_f
          end

          habilitadores.push @aspiracion_hab[dat][hab]
          @aspiracion_dat[dat] += @aspiracion_hab[dat][hab]/@points_hab[dat].keys.size
        end
        if @aspiracion_hab[dat] == @points_hab[dat]
          @aspiracion_hab[dat] = @recomendation_hab[dat] 
          @aspiracion_dat[dat] = @hab_params[dat].to_f 
        end
      else
        @points_hab[dat].keys.each do |hab|
          if @hab_params[hab] != "" and @hab_params[hab] != nil
            if !@aspiracion_hab.keys.include? dat
              @aspiracion_dat[dat] = 0
              @aspiracion_hab[dat] = {}
            end
            @aspiracion_hab[dat][hab] = @hab_params[hab].to_f
            habilitadores.push @aspiracion_hab[dat][hab]
            @aspiracion_dat[dat] += (@aspiracion_hab[dat][hab].to_f/@points_hab[dat].keys.size).round
          else
            habilitadores.push @recomendation_hab[dat][hab]
          end
        end
      end
    end
    @aspiracion_mat["alignment_score"] = 0
    
    Dat.all.each do |dat|
      @aspiracion_mat["maturity_score"] += @aspiracion_dat[dat.name.downcase.downcase]*dat.ponderador
    end
    alignment_mean = habilitadores.sum(0.0)/habilitadores.size
    num_sum = habilitadores.sum(0.0) {|element| (element - alignment_mean) ** 2}
    variance = num_sum / (habilitadores.size)  
    @aspiracion_mat["alignment_score"] = Math.sqrt(variance)
    respond_to do |format|
      format.json {render json: @aspiracion_hab}
      format.turbo_stream
    end
  end

  private

  def correct_user
    redirect_to root_path, notice: "No tienes permiso realizar esa acción." if @empresa != current_user.empresa
  end

  def correct_empresa
    redirect_to root_path, notice: "No tienes permiso realizar esa acción." if @empresa != @aspiracion.empresa
  end

  def correct_admin
    redirect_to root_path, notice: "No tienes permiso realizar definir una aspiración." if current_user.is_admin == "0"
  end

  def calculate_recomendation
    recomendation_sorted = @points_dat.sort_by{|k, v| v}
    list = {}
    recomendation_sorted.each do |element|
      list[element[0]] = element[1]
    end
    ponderators = {}
    keys = list.keys

    Dat.all.each do |dat|
      ponderators[dat.name.downcase.downcase] = dat.ponderador
    end
    madurez = @itdcon["maturity_score"]
    ptos = (@recomendation_mat["maturity_score"] - madurez)/ponderators[keys[0]]
    while ptos.to_i > 0
      madurez = 0
      keys.each do |key|
        madurez += list[key]*ponderators[key]
      end
      diff = 0 #la diferencia entre un habilitador y el siguiente
      list_aux = [] #habilitadores a subir puntaje
      (0...keys.length-1).each do |key|
        list_aux << keys[key]
        if list[keys[key]] < list[keys[key + 1]]
          diff = list[keys[key + 1]] -  list[keys[key]]
          break
        end
      end
      if diff == 0 #caso en que todos los habilitadores están con el mismo puntaje
        ptos = keys.length*(@recomendation_mat["maturity_score"] - madurez)
        resta = (ptos/keys.length).floor #cantidad a subir por habilitador (es el piso para que sea entero y no sume más de la cuenta)
        keys.each do |key|
          list[key] += resta
          ptos -= resta
        end
        if ptos > 0
          keys.each do |key|
            list[key] += 1
            ptos -= 1
            if ptos == 0
              break
            end
          end
        end
      else
        if list_aux.length > 1
          avrg_ponderator = 0
          list_aux.each do |key|
            avrg_ponderator += ponderators[key]
          end
          avrg_ponderator = avrg_ponderator/list_aux.length 
          ptos = (@recomendation_mat["maturity_score"] - madurez)/avrg_ponderator
        end
        if diff*list_aux.length <= ptos
          list_aux.each do |key|
            list[key] += diff
          end
          ptos -= diff*list_aux.length
        else
          resta = (ptos/keys.length).floor
          list_aux.each do |key|
            list[key] += resta
            ptos -= resta
          end
          if ptos > 0
            list_aux.each do |key|
              list[key] += 1
              ptos -= 1
              if ptos == 0
                break
              end
            end
          end
        end
      end
    end
    @recomendation_dat = list
  end

  def calculate_hab_recomendation
    habilitadores = []
    @aspiracion_dat.keys.each do |dat|
      recomendation_sorted = @points_hab[dat].sort_by{|k, v| v}
      list = {}
      recomendation_sorted.each do |element|
        list[element[0]] = element[1]
      end
      keys = list.keys
      ptos = (@aspiracion_dat[dat] - @points_dat[dat])*@points_hab[dat].keys.length
      while ptos.to_i >0
        diff = 0 #la diferencia entre un habilitador y el siguiente

app/helpers/aspiracions_helper.rb
module AspiracionsHelper
end

app/views/aspiracions/_accordion_flush.html.erb
<%= turbo_frame_tag "accordion_flush" do %>
  <div class="accordion accordion-flush" id="accordionFlushExample">
    <div class="accordion-item  border border-dark">
      <h4 class="accordion-header" id="flush-headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          <h4><%= "Aspiración de madurez y alineamiento"%></h4> 
        </button>
      </h4>
      <div id="flush-collapseOne" class="accordion-collapse collapse show" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
        <p class="ms-4", style="font-size:14px;"> Defina su aspiración del nivel de madurez y alineamiento.</p>
        <div class="accordion-body">
          <div class = "row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 "> 
              <%= render "maturity_graph", recomendation_mat: aspiracion_mat, itdcon: itdcon %>
            </div>
            <div class="d-flex flex-column flex-wrap justify-content-center col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12">
              <div class="d-flex align-items-center w-100">
                <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12 col-xs-12" >
                  <%= render "form_maturity", empresa: empresa, aspiracion: aspiracion, aspiracion_mat: aspiracion_mat, itdcon: itdcon %>
                </div>
                <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12 col-xs-12 " >
                  <div class="d-flex justify-content-around">
                    <div>
                      <p class="text-center"><b>Aspiración<br>de Madurez</b></p>
                      <%if recomendation_mat["maturity_score"].round > itdcon.maturity_score.round or (recomendation_mat["alignment_score"].round < itdcon.alignment_score.round and recomendation_mat["alignment_score"] > 0) %>
                        <h4 class="text-center"><b><%= aspiracion_mat["maturity_score"].round %></b></h4>
                      <%else%>
                        <h6 class="text-center"><b> -- </b></h6>
                      <%end%>
                    </div>
                    <div>
                      <p class="text-center"><b>Aspiración de<br>Alineamiento</b></p>
                      <%if recomendation_mat["maturity_score"].round > itdcon.maturity_score.round or (recomendation_mat["alignment_score"].round < itdcon.alignment_score.round and recomendation_mat["alignment_score"] > 0) %>
                        <h4 class="text-center"><b><%= aspiracion_mat["alignment_score"].round %></b></h4>
                      <%else%>
                        <h6 class="text-center"><b> -- </b></h6>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>
              <div class="d-flex justify-content-end w-100">
                <input type="submit" value="Enviar" form="maturity_form" class="btn btn-primary border border-dark me-4 mt-2">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item  border-bottom border-end border-start border-dark">
      <h4 class="accordion-header" id="flush-headingTwo">
        <%if recomendation_mat["maturity_score"].round > itdcon.maturity_score.round or (recomendation_mat["alignment_score"].round < itdcon.alignment_score.round and recomendation_mat["alignment_score"] > 0) %>
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
            <h4><%= "Aspiración por DATs"%></h4> 
          </button>
        <%else%>
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse" aria-expanded="false" aria-controls="flush-collapseTwo">
            <h4><%= "Aspiración por DATs"%></h4> 
          </button>
        <%end%>
      </h4>
      <%if recomendation_mat["maturity_score"].round > itdcon.maturity_score.round or (recomendation_mat["alignment_score"].round < itdcon.alignment_score.round and recomendation_mat["alignment_score"] > 0) %>
      <div id="flush-collapseTwo" class="accordion-collapse collapse show" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
      <%else%>
      <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
      <%end%>
        <p class="ms-4", style="font-size:14px;"> Defina su aspiración para cada capital.</p>
        <div class="accordion-body">
          <div class = "row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 ">
              <%= render "dat_graph", recomendation_dat: recomendation_dat, points_dat: points_dat, aspiracion_dat: aspiracion_dat, aspiracion_mat: aspiracion_mat %>
            </div>
            <div class="d-flex flex-column flex-wrap justify-content-center col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12">
              <div class="d-flex flex-wrap align-items-center w-100">
                <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12 col-xs-12" >
                  <%= render "form_dat", empresa: empresa, aspiracion: aspiracion, recomendation_dat: recomendation_dat, recomendation_mat: recomendation_mat, points_dat: points_dat  %>
                  <p style="font-size: 12px; margin-bottom: -2px"> Para el mejor alineamiento entre DATs debes subir los DATs a:</p>
                  <% points_dat.keys().each do |dat|%>
                    <div>
                      <%if recomendation_dat[dat].round - points_dat[dat].round > 0 %>
                        <p style="margin-bottom: -2px; font-size: 12px"><b><%= "Capital #{dat}: #{recomendation_dat[dat].round}" %></b></p>
                      <% end %>
                    </div>
                  <% end %>
                </div>
                <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12 col-xs-12 ">
                  <%= render "result_dat", aspiracion_mat: aspiracion_mat  %>
                  <div class="d-flex justify-content-end w-100">
                    <input type="submit" value="Enviar" form="submit_dat_form" class="btn btn-primary border border-dark me-4 mt-2">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render "hab_section", empresa: empresa, aspiracion: aspiracion, aspiracion_dat: aspiracion_dat, aspiracion_mat: aspiracion_mat, recomendation_hab: recomendation_hab, points_hab: points_hab, points_dat: points_dat, aspiracion_hab: aspiracion_hab, recomendation_mat: recomendation_mat%>
  </div>
<%end%>

app/views/aspiracions/_dat_graph.html.erb
 <div>
  <canvas id="myChart" height="350px"></canvas>
</div>
<script>
  label = [];
  values = [];
  maturity = [] ;
  recomendation = [];
  <% points_dat.keys.each do |dat|%>
    label.push("Capital <%= dat %>");
    values.push(<%= points_dat[dat].round%>);
    maturity.push(<%= aspiracion_mat["maturity_score"].round%>);
    recomendation.push(<%= recomendation_dat[dat].round%>);
  <%end%>
  ctx = document.getElementById('myChart');
  data = [{
      label: 'Puntaje Aspirado',
      type: 'line',
      data: maturity,
      backgroundColor: "red",
      borderColor:'red',
      pointRadius: 1,
    },
    {
      label: 'Puntaje por Capital',
      type: 'bar',
      data: values,
      fill: true,
      backgroundColor: "blue",
      borderColor:'blue'
    },
    {
      label: 'Aspiración Recomendada',
      type: 'bar',
      data: recomendation,
      fill: true,
      backgroundColor: "gray",
      borderColor:'gray'
  }];
  <% if aspiracion_dat.keys.length > 0 %>
    aspiracion = [];
    <% points_dat.keys.each do |dat|%>
      aspiracion.push(<%= aspiracion_dat[dat].round%>);
    <%end%>
    data.splice(2,0,{
    label: 'Aspiración Establecida',
    type: 'bar',
    data: aspiracion,
    fill: true,
    borderColor: '#FFFFF',
    backgroundColor: '#00000',
    })
  <%end%>
  new Chart(ctx, {
    data: {
    labels: label,
    datasets: data,
    },
    options: {
      maintainAspectRatio: false,
      plugins: {
        legend: {
          onClick: null,
        }
      },
      scales: {
        x: {
          stacked: true
        },
        y: { 
          ticks: {
            count: 101,
            callback: (value, index, values ) => {
              if ([0,30,55,75,90,100].includes(value)) {
                return value
              };
              if (value == 15) {
                return "Rezagado Digital"
              };
              if (value == 42) {
                return "Explorador Digital"
              };
              
              if (value == 65) {
                return "Adoptador Digital"
              };
              
              if (value == 82) {
                return "Líder Digital"
              };
              
              if (value == 95) {
                return "Disruptor Digital"
              };
            }
          },
          grid: {
            color: function(context) {
              let response = [];
              for (i = 0; i < context.scale.ticks.length; i++) {
                if (i == context.index) {
                  if (Number.isInteger(context.scale.ticks[i].label)) {
                    return "rgba(0, 0, 0, 0.2)"
                  } else {
                    return false
                  }
                }
              };
            }
          },
          min: 0, 
          max: 100,
        },
      },
      elements: {
        line: {
          borderWidth: 3
        }
      }
    },
  });   
</script>

app/views/aspiracions/_form_create.html.erb
<%= form_with(model: [empresa, aspiracion]) do |form| %>
  <% if aspiracion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aspiracion.errors.count, "error") %> prohibited this tobe from being saved:</h2>

      <ul>
        <% aspiracion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :empresa_id, value: empresa.id %>
  <%= form.hidden_field :alignment_score, value: aspiracion_mat["alignment_score"].round() %>
  <%= form.hidden_field :maturity_score, value: aspiracion_mat["maturity_score"].round() %>
  <% aspiracion_dat.keys.each do |dat|%>
    <%= form.hidden_field dat, value: aspiracion_dat[dat] %>
    <% if aspiracion_hab.keys.include? dat %>
      <% aspiracion_hab[dat].keys.each do |hab|%>
        <%= form.hidden_field hab, value: aspiracion_hab[dat][hab] %>
      <% end %>
    <%else%>
      <% recomendation_hab[dat].keys.each do |hab|%>
        <%= form.hidden_field hab, value: recomendation_hab[dat][hab] %>
      <% end %>
    <% end %>
  <% end %>
  <div>
    <%= form.submit "Definir Aspiración", class: "btn btn-primary  border border-dark " %>
  </div>
<% end %>

app/views/aspiracions/_form_dat.html.erb
<%= form_with(model: [empresa, aspiracion], url: update_dat_recomendation_path(empresa), method: :post, id: "submit_dat_form") do |form| %>
  <% if aspiracion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aspiracion.errors.count, "error") %> prohibited this tobe from being saved:</h2>

      <ul>
        <% aspiracion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%points_dat.keys.each do |dat|%>
    <div class="d-flex text-end align-items-center">
      <%= form.label dat.to_s, style: "display: block; font-size:13px;", class: "col-7 me-2 mb-2"  %>
      <%= form.number_field dat.to_s, placeholder: recomendation_dat[dat].round, max: 100, min: (points_dat[dat].round + 1), value: nil, class: "input col-4 mb-2"  %>
    </div>
  <%end%>
    <%= form.hidden_field :maturity_score, value: recomendation_mat["maturity_score"] %>
    <%= form.hidden_field :alignment_score, value: recomendation_mat["alignment_score"] %>
<% end %>

app/views/aspiracions/_form_maturity.html.erb
<%= form_with(model: [empresa, aspiracion], url: update_maturity_recomendation_path(empresa), method: :post, id: "maturity_form") do |form| %>
  <% if aspiracion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aspiracion.errors.count, "error") %> prohibited this tobe from being saved:</h2>

      <ul>
        <% aspiracion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="d-flex text-end align-items-center">
    <%= form.label "Madurez", style: "display: block; font-size:13px;", class: "col-7 me-2 mb-2" %>
    <%= form.number_field :maturity_score, placeholder: itdcon.maturity_score.round, max: 100, min: (itdcon.maturity_score.round + 1), value: aspiracion_mat["maturity_score"]>0 ? aspiracion_mat["maturity_score"].round : (aspiracion.maturity_score ? aspiracion.maturity_score.round : nil) , class: "input col-4 mb-2" %>
  </div>

  <div class="d-flex text-end align-items-center">
    <%= form.label "Alineamiento", style: "display: block; font-size:13px", class: "col-7 me-2 "%>
    <%= form.number_field :alignment_score, placeholder: itdcon.alignment_score.round, min: 0, max: (itdcon.alignment_score.round - 1), value: aspiracion_mat["maturity_score"]>0 ? aspiracion_mat["alignment_score"].round : (aspiracion.alignment_score ? aspiracion.alignment_score.round : nil), class: "input col-4" %>
  </div>
<% end %>

app/views/aspiracions/_result_dat.html.erb
<div class="d-flex justify-content-around">
  <div>
    <p class="text-center"><b>Aspiración<br>de Madurez</b></p>
    <%if aspiracion_mat["maturity_score"]%>
      <h4 class="text-center"><b><%= aspiracion_mat["maturity_score"].round %></b></h4>
    <%end%>
  </div>
  <div>
    <p class="text-center"><b>Aspiración de<br>Alineamiento</b></p>
    <%if aspiracion_mat["alignment_score"]%>
      <h4 class="text-center"><b><%= aspiracion_mat["alignment_score"].round %></b></h4>
    <%end%>
  </div>
</div>

app/views/aspiracions/_result_hab.html.erb
<div class="d-flex justify-content-around">
  <div>
    <p class="text-center"><b>Aspiración del<br>Capital <%=dat.capitalize%></b></p>
    <%if aspiracion_dat[dat]%>
      <h4 class="text-center"><b><%=aspiracion_dat[dat].round %></b></h4>
    <%end%>
  </div>
</div>

app/views/aspiracions/index.erb
<div class="container-fluid">
  <div class="main">
    <div class="shadow p-3 mb-5 bg-white rounded">  
      <script>
        let label = [];
        let values = [];
        let maturity = [] ;
        let recomendation = [];
        let ctx;
        let ctx2;
        let arbitratyLine;
        let data;
        let token;
        var myChart;
        let aspiracion;
      </script>
      <%= turbo_frame_tag "accordion_flush" do %>
        <%= render "accordion_flush", empresa: @empresa, aspiracion: @empresa.aspiracion.build, recomendation_mat: @recomendation_mat, itdcon: @itdcon, recomendation_dat: @recomendation_dat,  recomendation_hab: @recomendation_hab, points_dat: @points_dat, points_hab: @points_hab, aspiracion_mat: @aspiracion_mat, aspiracion_dat: @aspiracion_dat, aspiracion_hab: @aspiracion_hab %>
      <%end%>
      
    </div>
  </div>
</div>
