config/routes.rb
Rails.application.routes.draw do
  get 'con_verificadors/index'
  root "homes#index"
  post 'empresas/:empresa_id/aspiracions/update_maturity_recomendation', to: 'aspiracions#update_maturity_recomendation', as: 'update_maturity_recomendation'
  post 'empresas/:empresa_id/aspiracions/update_dat_recomendation', to: 'aspiracions#update_dat_recomendation', as: 'update_dat_recomendation'
  post 'empresas/:empresa_id/aspiracions/update_hab_recomendation', to: 'aspiracions#update_hab_recomendation', as: 'update_hab_recomendation'
  post 'empresas/:empresa_id/users/invite_member', to: 'users#invite_member', as: 'invite_member'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    invitations: 'users/invitations'
  }, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get "empresas/:empresa_id/users", to: "users#index", as: "empresa_users"
  get "users/:id", to: "users#show", as: "user"
  resources :empresas, only: [:show] do 
    resources :areas, only: [:create]
    resources :itdcons, only: [:index, :show, :create, :update, :destroy] do
      resources :itdinds, only: [:show, :edit, :update]
      resources :itdareas, only: [:show, :update]
      resources :com_verificadors, only: [:index]
    end
    resources :aspiracions, only: [:index, :show, :create, :update]
  end
  resources :itdsins , only: [:new, :create, :show]
  get "homes/example"

  get '/*paths', to: 'unhandled#show'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :lastname, presence: true
  belongs_to :empresa
  belongs_to :area, optional: true
  has_many :itdinds, dependent: :nullify
  validate :password_complexity
  accepts_nested_attributes_for :empresa
  private

  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-])/

    errors.add :password, ' no cumple los requisitos de complejidad'
  end

  def block_from_invitation?
    #If the user has not been confirmed yet, we let the usual controls work
    if confirmed_at.blank?
      return invited_to_sign_up?
    else #if the user was confirmed, we let them in (will decide to accept or decline invitation from the dashboard)
      return false
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    root_path
  end
end

app/controllers/users/invitations_controller.rb
# frozen_string_literal: true

class Users::InvitationsController < DeviseController
  before_action :check_session
  prepend_before_action :resource_from_invitation_token, only: [:edit, :destroy] #ADD LOG OUT IF LOGED IN
  # GET /resource/invitation/new
  def new
    super
  end

  # POST /resource/invitation
  def create
    super
  end

  # GET /resource/accept?invitation_token=abcdef
  def edit
    if resource.name ==nil and !resource.invitation_accepted?
      set_minimum_password_length
      resource.invitation_token = params[:invitation_token]
      render :edit
    elsif resource.invitation_accepted?
      redirect_to new_user_session_path
    else
      resource.accept_invitation()
      resource.save
      redirect_to new_user_session_path
    end
  end

  # PUT /resource/invitation
  def update
    raw_invitation_token = update_resource_params[:invitation_token]
    resource = accept_resource
    invitation_accepted = resource.errors.empty?
    if invitation_accepted
      sign_in(resource)
      redirect_to root_path
    else
      resource.invitation_token = raw_invitation_token
      redirect_to "/resource/accept?invitation_token=#{raw_invitation_token}"
    end
  end

  # GET /resource/invitation/remove?invitation_token=abcdef
  def destroy
    resource.destroy
    set_flash_message :notice, :invitation_removed if is_flashing_format?
    redirect_to root_path
  end

  protected
    def check_session
      if current_user
        sign_out(current_user)
      end
    end
    # This is called when creating invitation.
    # It should return an instance of resource class.
    def invite_resource (&block)
      # skip sending emails on invite
      resource_class.invite!(invite_params, current_inviter, &block)
    end

    # This is called when accepting invitation.
    # It should return an instance of resource class.
    def accept_resource
      resource = resource_class.accept_invitation!(update_resource_params)
      # Report accepting invitation to analytics
      resource
    end

    def resource_from_invitation_token
      unless params[:invitation_token] && self.resource = resource_class.find_by_invitation_token(params[:invitation_token], true)
        set_flash_message(:alert, :invitation_token_invalid) if is_flashing_format?
        redirect_to invalid_token_path_for(resource_name)
      end
    end

    def update_resource_params
      devise_parameter_sanitizer.sanitize(:accept_invitation)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    build_resource
    resource.build_empresa
    yield resource if block_given?
    respond_with resource
  end

  # POST /resource
  def create
    parameters = sign_up_params
    build_resource(parameters)
    if resource.valid?
      @empresa = Empresa.new(parameters[:empresa_attributes])
      if @empresa.save
        resource.empresa = @empresa
        resource.is_admin = 1
      end
    end
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      render :new, status: :unprocessable_entity
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :lastname, :empresa_attributes => [:name, :rut, :size, :sector]])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :lastname])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_empresa, only: [:index, :invite_member]
  before_action :get_user, only: [:show]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show]#cualquier miembro del equipo?
  before_action :correct_user_empresa, only: [:index, :invite_member]
  before_action :correct_user_invite, only: [:invite_member]
  
  def create
  end

  def show #SHOW INVITATIONS PENDING
    @user = User.find(params[:id])
  end

  def index
    @users = @empresa.users.order(id: :asc).all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_index_path
  end

  def invite_member #CHECK IF EMAIL IS CORRECT IN VIEW   
    user = User.find_by(email: invitation_param[:email])
    if user
      if user != current_user
        if (user.empresa_id == current_user.empresa_id and !user.accepted_or_not_invited?) #ALERTA SI EXISTE
          current_user.invite!(user)
          flash[:alert] = "Invitación reenviada con exito"
        elsif user.empresa_id != current_user.empresa_id
          #ADD ALERT
          flash[:alert] = "Usuario ya pertenece a otra organización"
        else
          #ADD ALERT
          flash[:alert] = "Usuario ya es parte de la organización"
        end
      else
        flash[:alert] = "No puedes agregarte a ti mismo"
      end
    else

      User.invite!({email: invitation_param[:email], empresa: current_user.empresa}, current_user)
      flash[:alert] = "Usuario invitado con exito"
    end
    redirect_to empresa_users_path(current_user.empresa_id)
  end

  private

  def correct_user
    redirect_to root_path, notice: "No tienes permiso para realizar esa acción." if !(@user == current_user)
  end
  def correct_user_invite
    redirect_to empresa_users_path(current_user.empresa_id), notice: "No tienes permiso para realizar esa acción." if (current_user.is_admin == "0")
  end
  def correct_user_empresa
    redirect_to root_path, notice: "No tienes permiso para realizar esa acción." if current_user.empresa != @empresa
  end

  def get_empresa
    @empresa = Empresa.find_by(id: params[:empresa_id])
    redirect_to root_path, notice: "Acción invalida." if !@empresa
  end 

  def get_user
    @user = User.find_by(id: params[:id])
    redirect_to root_path, notice: "Acción invalida." if !@user
  end 

  def invitation_param
    params.require(:user).permit(:email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: [empresa, user], url: invite_member_path(empresa), method: :post) do |form| %>
  <% if user.errors.any? %>
    <div>
      <h2><%= pluralize(user.errors.count, "error") %>, necesitas llenar los siguientes campos: </h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modal fade" id="exampleModalEquipo" tabindex="-1" aria-labelledby="exampleModalEquipoLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalEquipoLabel">Invitar miembro</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class = "container">
            <div class="main mt-4">
              <%= form.label "Email del invitado" %> <br />
              <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary" name="submit" value="Submit">Agregar integrante</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="main mt-4 position-relative">
  <%= render partial: "form", locals: {empresa: @empresa, user: @empresa.users.build}%>
  <% if current_user.is_admin%>
    <button class= "position-absolute top-0 end-0 mt-2 me-2 btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModalEquipo">
      Invitar Miembro
    </button>
  <%end%>
  <h3 >Equipo</h3>
  <div  class="row">
    <div id="size_fixed" class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-xs-12">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <div class=" d-flex flex-wrap justify-content-start align-items-center">
                  <%= image_tag "logos/profile.png", height: 45%>
                  <div class= "ms-2">
                    <%= "#{user.name} #{user.lastname}" %> 
                    <br>
                    <%= user.email %>
                  </div>
                </div>
              </td>
              <td>
                <div class=" d-flex flex-wrap me-3 justify-content-end ">
                  <div class="align-self-center">
                    <% if !user.accepted_or_not_invited?%>
                      Pendiente
                    <% else%>
                      <%if user.is_admin%>
                        Administrador
                      <%else%>
                        Aceptado
                      <%end%>
                    <%end%>
                  </div>
                  <div class="dropend">
                    <div type="button" id="dropdownMenuButtonEquipo1" data-bs-toggle="dropdown" aria-expanded="false">
                      <%= image_tag "logos/options.png", height: 40, class: "ms-3" %>
                    </div>
                    <% if user == current_user or current_user.is_admin%>                    
                      <ul class="dropdown-menu ms-3" aria-labelledby="dropdownMenuButtonEquipo1">
                        <%= link_to "Ver Perfil", user_path(user.id), class:"profileoptions" %>
                      </ul>
                    <%end%>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main mt-4">
    <div class="tile is-ancestor">
      <div class="tile is-4 is-vertical is-parent">
      </div>
      <div class="tile is-parent">
        <div class="tile is-child box">
          <p class="title"><%= @user.name%></p>
          <p><%=@user.email%></p>
          <% if current_user == @user%>
            <%= button_to "Eliminar Usuario", user_registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class:"button is-info is-light" %>
          <%end%> 
        </div>
      </div>
    </div>


    <button class="button is-info is-light">
        <%= link_to "Volver a la pagina principal", root_path %>
    </button>
    <button class="button is-info is-light">
        <%= link_to "Volver al listado de Usuarios", empresa_users_path(@user.empresa)%>
    </button>

</div>